# Maintainer: Alexey Baranov <a.baranov@office.ngs.ru>
pkgname=repod
pkgver=${PKGVER:-autogenerated}
pkgrel=${PKGREL:-1}
pkgdesc="repository management service"
arch=('x86_64')
license=()
md5sums=('SKIP')
depends=()
makedepends=(
	'go'
	'git'
)
backup=()
branch=${BRANCH:-master}
source=(
	"git+ssh://git.rn/devops/repod.git#branch=$branch"
)

pkgver() {
	cd "$srcdir/$pkgname"
	local date=$(git log -1 --format="%cd" --date=short | sed s/-//g)
	local count=$(git rev-list --count HEAD)
	local commit=$(git rev-parse --short HEAD)
	echo "$date.${count}_$commit"
}

build() {
	cd "$srcdir/$pkgname"

	if [ -L "$srcdir/$pkgname" ]; then
		rm "$srcdir/$pkgname" -rf
		mv "$srcdir/.go/src/$pkgname/" "$srcdir/$pkgname"
	fi

	rm -rf "$srcdir/.go/src"

	mkdir -p "$srcdir/.go/src"

	export GOPATH="$srcdir/.go"

	mv "$srcdir/$pkgname" "$srcdir/.go/src/"

	cd "$srcdir/.go/src/$pkgname/"
	ln -sf "$srcdir/.go/src/$pkgname/" "$srcdir/$pkgname"

	git submodule init
	git submodule update

	echo "Running 'go get'..."
	GO15VENDOREXPERIMENT=1 go get \
		-ldflags="-X main.version=$pkgver-$pkgrel"
}

package() {
	bin=$pkgdir/usr/bin/
	systemd=$pkgdir/usr/lib/systemd/system/
	service=$systemd/repod.service.d/

	install -d $bin $systemd $service

	cp $srcdir/.go/bin/repod $bin
	cp $srcdir/repod/systemd/repod.service $systemd
	cp $srcdir/repod/systemd/default.conf $service/.conf
}

# vim: noexpandtab
