#!/bin/bash

set -euo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
source ../vendor/github.com/reconquest/import.bash/import.bash

import:source "github.com/reconquest/test-runner.bash"

:build() {
    cd .. && go build -o ./tests/repod
}

:main() {
    trap :cleanup EXIT
    :cleanup() {
        :
    }

    :build

    test-runner:run "${@}"
}

:main "${@}"
