#!/bin/bash

set -euo pipefail

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
source ../vendor/github.com/reconquest/import.bash/import.bash

mode=${mode:-all}

import:source "github.com/reconquest/tests.sh"
import:source "github.com/reconquest/test-runner.bash"
import:source "github.com/reconquest/go-test.bash"

:init() {
    tests:init
}

:build() {
    cd ../
    go-test:set-output-dir $(pwd)
    go-test:build repod.test 2>/dev/null
}

:run() {
    test-runner:run "${@}"
}

:main() {
    trap :cleanup EXIT
    :cleanup() {
        go-test:merge-coverage
    }

    :init
    :build

    if [[ $mode == "all" ]]; then
        echo "[running] cli mode"
        mode=cli :run "${@}"
        echo "[running] daemon mode"
        mode=daemon
    fi

    :run "${@}"
}

:main "${@}"
